name: sfv-dsb
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - numpy>=1.24
  - scipy>=1.11
  - pandas>=2.1
  - matplotlib>=3.8
  - pyyaml>=6.0
  - pip
  - pip:
      # keep empty unless you add extras later
      - 
